apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"build.knative.dev/v1alpha1","kind":"Install","metadata":{"name":"example-install"},"spec":{"size":3}}]'
    capabilities: Basic Install
  name: knative-build-operator.v0.4.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: The Knative Build Installation
      displayName: Installation
      kind: Install
      name: installs.build.knative.dev
      version: v1alpha1
    - description: Create and run on-cluster processes to completion
      displayName: Build
      kind: Build
      name: builds.build.knative.dev
      version: v1alpha1
    - description: Encapsulates a configurable, reusable build process
      displayName: Build Template
      kind: BuildTemplate
      name: buildtemplates.build.knative.dev
      version: v1alpha1
    - description: Encapsulates a cluster-scoped build process
      displayName: Cluster Build Template
      kind: ClusterBuildTemplate
      name: clusterbuildtemplates.build.knative.dev
      version: v1alpha1
  description: Placeholder description
  displayName: Knative Build Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - namespaces
          - secrets
          - events
          - serviceaccounts
          - configmaps
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds
          - buildtemplates
          - clusterbuildtemplates
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds/status
          - buildtemplates/status
          - clusterbuildtemplates/status
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - caching.internal.knative.dev
          resources:
          - images
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - deletecollection
          - patch
          - watch
        - apiGroups:
          - policy
          resourceNames:
          - knative-build
          resources:
          - podsecuritypolicies
          verbs:
          - use
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          - anyuid
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - extensions
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - build.knative.dev
          resources:
          - '*/finalizers'
          verbs:
          - update
        - apiGroups:
          - policy
          resources:
          - podsecuritypolicies
          verbs:
          - create
          - update
          - patch
          - get
        - apiGroups:
          - build.knative.dev
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - create
          - update
          - delete
        serviceAccountName: knative-build-operator
      deployments:
      - name: knative-build-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: knative-build-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: knative-build-operator
            spec:
              containers:
              - command:
                - knative-build-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: knative-build-operator
                image: quay.io/jcrossley3/knative-build-operator:v0.4.0
                args: ["--olm", "--install"]
                imagePullPolicy: Always
                name: knative-build-operator
                resources: {}
              serviceAccountName: knative-build-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - knative-build-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - build.knative.dev
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: knative-build-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - serverless
  - CI
  - CD
  - pipeline
  - build
  maintainers:
  - email: vdemeest@redhat.com
    name: Vincent Demeester
  maturity: alpha
  provider:
    name: Knative Community
  version: 0.4.0
