apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-build-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: knative-build-operator
  template:
    metadata:
      labels:
        name: knative-build-operator
    spec:
      serviceAccountName: knative-build-operator
      containers:
        - name: knative-build-operator
          image: quay.io/openshift-knative/knative-build-operator:v0.4.0
          command:
          - knative-build-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "knative-build-operator"
