apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: knative-build-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - knative-build-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - build.knative.dev
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-build-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "secrets", "events", "serviceaccounts", "configmaps"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["build.knative.dev"]
    resources: ["builds", "buildtemplates", "clusterbuildtemplates"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  # We enable the status subresource on the templates CRDs so metadata.generation
  # bumping will work in 1.11
  - apiGroups: ["build.knative.dev"]
    resources: ["builds/status", "buildtemplates/status", "clusterbuildtemplates/status"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["caching.internal.knative.dev"]
    resources: ["images"]
    verbs: ["get", "list", "create", "update", "delete", "deletecollection", "patch", "watch"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["knative-build"]
    verbs: ["use"]

  # The above rules are from upstream. The remaining are
  # required for either OpenShift or our operator

  - apiGroups:
    - security.openshift.io
    resources:
    - securitycontextconstraints
    verbs:
    - use
    resourceNames:
    - privileged
    - anyuid
  - apiGroups:
    - extensions
    resources:
    - deployments/finalizers
    verbs:
    - update
  - apiGroups:
    - build.knative.dev
    resources:
    - '*/finalizers'
    verbs:
    - update
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    verbs:
    - create
    - update
    - patch
    - get
  - apiGroups:
    - build.knative.dev
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - create
    - update
    - delete
